In [1]:
x=5

In [2]:
import pandas as pd

In [6]:
df = pd.read_csv("Titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
cols_to_drop = ["PassengerId", "Name", "Ticket"]

In [8]:
def Drop_unnecessary_features(df, cols_to_drop):
    df = df.drop(cols_to_drop, axis=1)
    return df

In [9]:
df = Drop_unnecessary_features(df, cols_to_drop)
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [10]:
def Check_data_type(df):
    result = pd.DataFrame({
        "Column Name": df.columns,
        "Data Type": df.dtypes,
        "Unique Values": df.nunique()
    })
    
    return result.T

In [11]:
Check_data_type(df)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
Column Name,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
Data Type,int64,int64,str,float64,int64,int64,float64,str,str
Unique Values,2,3,2,88,7,7,248,147,3